//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InlineQueryResult {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InlineQueryResult() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.InlineQueryResult", typeof(InlineQueryResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;
        ///Artists: {2}
        ///Release date: {3}
        ///        .
        /// </summary>
        public static string AlbumContent {
            get {
                return ResourceManager.GetString("AlbumContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0}
        ///Album
        ///        .
        /// </summary>
        public static string AlbumDescription {
            get {
                return ResourceManager.GetString("AlbumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;
        ///{2}
        ///        .
        /// </summary>
        public static string ArtistContent {
            get {
                return ResourceManager.GetString("ArtistContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0}
        ///Artist
        ///        .
        /// </summary>
        public static string ArtistDescription {
            get {
                return ResourceManager.GetString("ArtistDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;
        ///Owner: {2}
        ///        .
        /// </summary>
        public static string PlaylistContent {
            get {
                return ResourceManager.GetString("PlaylistContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Owner: {0}
        ///Playlist
        ///        .
        /// </summary>
        public static string PlaylistDescription {
            get {
                return ResourceManager.GetString("PlaylistDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;
        ///Artists: {2}
        ///Album: &lt;a href=&quot;{3}&quot;&gt;{4}&lt;/a&gt;
        ///Duration: {5}
        ///        .
        /// </summary>
        public static string TrackContent {
            get {
                return ResourceManager.GetString("TrackContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///{0}
        ///Track
        ///        .
        /// </summary>
        public static string TrackDescription {
            get {
                return ResourceManager.GetString("TrackDescription", resourceCulture);
            }
        }
    }
}
