// <auto-generated />
namespace Bot.Migrations

open System
open Bot.Data
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata

[<DbContext(typeof<AppDbContext>)>]
[<Migration("20220709205736_Init")>]
type Init() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Users"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<Int64>(
                        nullable = false
                        ,``type`` = "bigint"
                    ).Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                SpotifyId =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "text"
                    )
                SpotifyRefreshToken =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "text"
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Users", (fun x -> (x.Id) :> obj)
                    ) |> ignore
                )
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Users"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63) |> ignore

        modelBuilder.Entity("Bot.Data.User", (fun b ->

            b.Property<Int64>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                |> ignore

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<Int64>("Id")) |> ignore

            b.Property<string>("SpotifyId")
                .IsRequired(true)
                .HasColumnType("text")
                |> ignore

            b.Property<string>("SpotifyRefreshToken")
                .IsRequired(true)
                .HasColumnType("text")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Users") |> ignore

        )) |> ignore

